ALTER TABLE `pages` ADD COLUMN `status` VARCHAR(20) DEFAULT 'published';
ALTER TABLE `pages` ADD COLUMN `featured` TINYINT(1) DEFAULT 0;
ALTER TABLE `pages` ADD COLUMN `canonical_url` VARCHAR(255) DEFAULT '';
ALTER TABLE `pages` ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `pages` ADD COLUMN `seo_schema` TEXT;
ALTER TABLE `pages` ADD COLUMN `meta_keywords` TEXT;
ALTER TABLE `pages` ADD COLUMN `is_index` TINYINT(1) DEFAULT 1;
